[project]
name = "ricklm"
version = "0.1.0"
description = "Intuitive library to test LLMs"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "attrs>=25.4.0",
    "transformers>=5.0.0",
]
